#Common
resolution: 30
domain: [-1, 1]
batch_size: 128
dims: 3
verbose: 1 #1 for one time, general stuff, 2 for in depth
pre_trained_path: With positional encoding, temperature, convex, relu, high ent.t #models/model.t

#Batched env
num_init_points: 3
T: 100
time_bounds: [5, 7]
time_constants: [12, 12, 2] #If using pointwise, needs to match dims. Last is c
expand_size: 25
use_GP: True #Turn off if doing random

#GPY
GP_learning_rate: 0.1 #0.1
GP_training_iters: 50 #150
approximate: False
noise: None
kernel_classes: [RBF]
operation: mul

#Random function
functions: [convex] #[convex, rosenbrock, himmelblau] #Rosenbrock or convex for now
convex_a: [0.01, 0.5]
convex_b: [0.01, 0.5]
rosenbrock_a: [5, 10]
rosenbrock_b: [50, 100]
himmelblau_a: [8, 14] 
himmelblau_b: [4, 10]
noise_scale: 1.5
noise_correlation: 2.5