#Common
resolution: 30
domain: [-1, 1]
batch_size: 1024
dims: 2
verbose: 1 #1 for one time, general stuff, 2 for in depth
pre_trained_path: models/model.t

#Batched env
num_init_points: 3
T: 200
time_bounds: [5, 7]
expand_size: 50
use_GP: True #Turn off if doing random

#GPY
GP_learning_rate: 0.1
GP_training_iters: 200
approximate: False
noise: None
kernels: [RBF, Matern] #Only RBF and Matern

#Random function
function: rosenbrock
a: [0.01, 0.5]
b: [0.01, 0.5]
rosenbrock_a: [5, 10]
rosenbrock_b: [50, 100]
noise_scale: 4 #0.5
noise_correlation: 1
