#Common
resolution: 30
domain: [0, 1]
batch_size: 128
dims: 2
verbose: 1 #1 for one time, general stuff, 2 for in depth
pre_trained_path: models/model.t

#Batched env
num_init_points: 3
T: 200
time_bounds: [5, 7]
expand_size: 50
use_GP: True #Turn off if doing random

#GPY
GP_learning_rate: 0.1
GP_training_iters: 200
approximate: False
noise: None
kernels: [RBF, Matern] #Only RBF and Matern


#Random function
a: [0.01, 5]
b: [0.01, 5]
noise_scale: 2.5
noise_correlation: 3.5
