#Common
resolution: 30
domain: [-1, 1]
batch_size: 1024
dims: 2
verbose: 1 #1 for one time, general stuff, 2 for in depth
pre_trained_path: With positional encoding, temperature, mixed func.t #models/model.t

#Batched env
num_init_points: 3
T: 200
time_bounds: [5, 7]
expand_size: 25
use_GP: True #Turn off if doing random

#GPY
GP_learning_rate: 0.1
GP_training_iters: 200
approximate: False
noise: None
kernels: [RBF, Matern] #Only RBF and Matern

#Random function
functions: [convex, rosenbrock] #Rosenbrock or convex for now
convex_a: [0.01, 0.5]
convex_b: [0.01, 0.5]
rosenbrock_a: [5, 10]
rosenbrock_b: [50, 100]
noise_scale: 1.5
noise_correlation: 2.5

#PPO
total_timesteps: 10000000
anneal_lr: True
gae_lambda: 0.95
num_minibatches: 1
update_epochs: 4
norm_adv: True
clip_coef: 0.2
clip_vloss: True
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: 0.3

ent_coef: 0.02
num_steps: 32
learning_rate: 2.5e-4
gamma: 1
weight_decay: 1.0e-4

pre_trained: True